export interface Track {
  id: number
  title: string
  duration: string
  genre: string
  plays: number
  likes: number
  comments: number
}

export const tracks: Track[] = [
  { id: 1, title: "Let Me See You Go to Work", duration: "3:42", genre: "big room, tech house, hip hop", plays: 14, likes: 4, comments: 0 },
  { id: 2, title: "Low Lights, High Danger", duration: "7:07", genre: "big room, edm, cinematic", plays: 18, likes: 1, comments: 0 },
  { id: 3, title: "One Night Only", duration: "7:59", genre: "electro-funk, hip-hop", plays: 32, likes: 1, comments: 0 },
  { id: 4, title: "The OS of Funk", duration: "4:00", genre: "Old School Hip-Hop, Disco-Funk Fusion", plays: 23, likes: 3, comments: 0 },
  { id: 5, title: "Go Hard (We Funk)", duration: "7:59", genre: "hip hop, electronic, ambient", plays: 29, likes: 3, comments: 0 },
  { id: 6, title: "Blue Money", duration: "4:24", genre: "electronic, lo-fi hip-hop, psychedelic", plays: 40, likes: 4, comments: 0 },
  { id: 7, title: "The Devil's Summer", duration: "5:49", genre: "90s West Coast G-Funk, orchestral noir", plays: 29, likes: 5, comments: 0 },
  { id: 8, title: "Countdown", duration: "4:46", genre: "drum & bass, neurofunk, uptempo drill", plays: 29, likes: 6, comments: 0 },
  { id: 9, title: "Good For Nothin' But Love", duration: "5:27", genre: "hip hop, funk, electronic", plays: 20, likes: 3, comments: 0 },
  { id: 10, title: "Moonshot Blues AKA: HODL Odyssey", duration: "6:43", genre: "folk-rock, progressive rock, synthwave", plays: 36, likes: 10, comments: 0 },
  { id: 11, title: "Let Me Light It Up", duration: "5:01", genre: "house, dance, electronic", plays: 26, likes: 7, comments: 0 },
  { id: 12, title: "A Musical Journey (Stereo FX Club Mix)", duration: "7:59", genre: "hip hop, Afrobeat, jazz", plays: 45, likes: 9, comments: 2 },
  { id: 13, title: "Juice & Groove", duration: "5:29", genre: "trap, hip hop, afrobeat", plays: 45, likes: 7, comments: 0 },
  { id: 14, title: "Back For It", duration: "2:46", genre: "Glitch Disco, trap, EDM, Nu-Disco Funk", plays: 32, likes: 4, comments: 0 },
  { id: 15, title: "DJ Rap Battle", duration: "3:06", genre: "breakbeat, hip hop, club", plays: 45, likes: 5, comments: 0 },
  { id: 16, title: "Smoke Streams", duration: "4:07", genre: "big room trap, cinematic electronic, dance/club", plays: 62, likes: 2, comments: 0 },
  { id: 17, title: "Glitch in the Machine", duration: "2:07", genre: "West Coast hip-hop, G-funk, trap", plays: 26, likes: 2, comments: 0 },
  { id: 18, title: "420 on the Coast", duration: "3:54", genre: "West Coast hip hop, G-funk, party anthem", plays: 32, likes: 1, comments: 0 },
  { id: 19, title: "NEURAL IGNITION", duration: "4:24", genre: "ambient, experimental electronic, bass music", plays: 23, likes: 1, comments: 0 },
  { id: 20, title: "Love No More", duration: "3:52", genre: "experimental house, disco, IDM", plays: 114, likes: 4, comments: 0 },
  { id: 21, title: "Epic Tech AI Website is Live!", duration: "2:39", genre: "West Coast hip hop, G-funk, party rap", plays: 23, likes: 1, comments: 0 },
  { id: 22, title: "Coast to Coast High's", duration: "3:34", genre: "West Coast hip-hop, G-funk, party anthem", plays: 40, likes: 1, comments: 0 },
  { id: 23, title: "Outta Here", duration: "3:06", genre: "West Coast hip hop, G-funk, party anthem", plays: 20, likes: 1, comments: 0 },
  { id: 24, title: "420 Coastal Blaze", duration: "3:29", genre: "West Coast hip-hop, party rap, trap", plays: 23, likes: 2, comments: 0 },
  { id: 25, title: "Gimme 30 Seconds", duration: "2:44", genre: "hip hop, turntablism, trap, chopped and screwed", plays: 16, likes: 1, comments: 0 },
  { id: 26, title: "420 Rabbit Hole", duration: "4:00", genre: "Glitchy synths, slow burns, atmospheric layers", plays: 10, likes: 1, comments: 0 },
  { id: 27, title: "White Rabbit", duration: "3:18", genre: "Soundtrack of Seduction, Breathless Vocals", plays: 9, likes: 1, comments: 0 },
  { id: 28, title: "It's Easter N Happy 420", duration: "3:43", genre: "Glitchy synths, slow burns, Live DJ Session", plays: 12, likes: 1, comments: 1 },
  { id: 29, title: "Smoken Tokens", duration: "2:48", genre: "Live DJ Session, atmospheric layers", plays: 12, likes: 1, comments: 0 },
  { id: 30, title: "Smoken Tokens (Extended)", duration: "3:58", genre: "Glitchy synths, textured soundscape", plays: 20, likes: 1, comments: 0 },
  { id: 31, title: "Peach Vibes", duration: "4:00", genre: "live dj Pulse, turntablism, R&B, Sensual", plays: 14, likes: 1, comments: 0 },
  { id: 32, title: "Whispered Heat", duration: "3:26", genre: "turntablism, R&B, Breathless Vocals", plays: 16, likes: 1, comments: 0 },
  { id: 33, title: "Higher Low", duration: "3:19", genre: "80s pop-rock, gospel, R&B", plays: 20, likes: 1, comments: 0 },
  { id: 34, title: "Highr Low", duration: "3:39", genre: "80s pop-rock vibe with gospel and R&B influences", plays: 9, likes: 1, comments: 0 },
  { id: 35, title: "Higher Low (Remix)", duration: "3:20", genre: "Higher Love vibe, 80s synth-pop, soaring vocals", plays: 23, likes: 1, comments: 0 },
  { id: 36, title: "DJ Smoke Stream", duration: "4:00", genre: "Live, DJ, Club, BeatJuggling, TurntableMastery", plays: 20, likes: 1, comments: 0 },
  { id: 37, title: "Digital Through Out The Years", duration: "2:50", genre: "heartfelt lyrics, late 60s/70s, warm analog tones", plays: 12, likes: 1, comments: 0 },
  { id: 38, title: "It Takes Two to Make a Thing Go Right", duration: "3:35", genre: "Turntablism, disco, experimental house", plays: 14, likes: 1, comments: 0 },
  { id: 39, title: "Eastie Boys", duration: "3:08", genre: "Turntablism, Vaportrap, House, Scratches", plays: 32, likes: 2, comments: 0 },
  { id: 40, title: "Paul Revere", duration: "3:00", genre: "Turntablism, Sample Scratches, disco", plays: 14, likes: 1, comments: 0 },
  { id: 41, title: "Sweet Roxanne", duration: "3:10", genre: "Turntablism, Sample Scratches, orchestral", plays: 20, likes: 1, comments: 0 },
  { id: 42, title: "Bille Jean Super Freaky", duration: "3:03", genre: "Turntablism, Sample Scratches, disco", plays: 20, likes: 1, comments: 0 },
  { id: 43, title: "The Message From Planet Rock", duration: "3:14", genre: "Turntablism, Sample Scratches, disco", plays: 16, likes: 1, comments: 0 },
  { id: 44, title: "Stream Planet", duration: "2:24", genre: "Old-School Hip-Hop, Funky, Rapper's Delight bass", plays: 23, likes: 1, comments: 0 },
  { id: 45, title: "Resonance Cascade", duration: "3:23", genre: "House, Vaportrap, Turntablism, Scratches", plays: 20, likes: 1, comments: 0 },
  { id: 46, title: "DJ Smoke Stream (Club Mix)", duration: "2:15", genre: "House, Vaportrap, Turntablism, Scratches", plays: 16, likes: 1, comments: 0 },
  { id: 47, title: "Echo Chamber", duration: "3:27", genre: "House, Vaportrap, Turntablism, Scratches", plays: 23, likes: 1, comments: 0 },
  { id: 48, title: "Rewind & Riot", duration: "3:13", genre: "Big House, Vaportrap, Turntablism, Scratches", plays: 16, likes: 1, comments: 0 },
  { id: 49, title: "Sample Mayhem", duration: "3:57", genre: "House, Vaportrap, Turntablism, Scratches", plays: 14, likes: 1, comments: 0 },
  { id: 50, title: "Big Room Riots", duration: "3:16", genre: "vocal house, vaportrap, turntablism", plays: 10, likes: 1, comments: 0 },
  { id: 51, title: "Sample Junkie", duration: "3:27", genre: "vocal house, vaportrap, turntablism", plays: 16, likes: 1, comments: 0 },
  { id: 52, title: "Till Now's Requiem (Remastered)", duration: "3:18", genre: "Raw vocals, Minimal synth, Erotic glitchcore", plays: 10, likes: 1, comments: 0 },
  { id: 53, title: "Till Now's Requiem", duration: "3:14", genre: "Distorted industrial beat, Big House", plays: 16, likes: 1, comments: 0 },
  { id: 54, title: "240", duration: "3:52", genre: "Ambient Erotica, Ethereal R&B, Electronica", plays: 12, likes: 1, comments: 0 },
  { id: 55, title: "Heatwave", duration: "3:59", genre: "Moombahton, Big House Summer Vibes, Club", plays: 14, likes: 1, comments: 0 },
  { id: 56, title: "Uptown Dreams (Are Made of This)", duration: "4:00", genre: "Funk House, Nu-Disco Mashup, Synthwave Funk", plays: 16, likes: 1, comments: 0 },
  { id: 57, title: "Midnight Fix", duration: "3:19", genre: "Dark Club, Heavy Bass, Underground Rave", plays: 12, likes: 1, comments: 0 },
  { id: 58, title: "Jungle Pulse", duration: "4:00", genre: "Moombahton, Big House, Club-Ready", plays: 10, likes: 1, comments: 0 },
  { id: 59, title: "Shockwave", duration: "3:11", genre: "Electronic, Bass Music", plays: 8, likes: 1, comments: 0 },
  { id: 60, title: "Get Together Lucky", duration: "3:08", genre: "Electronic, Dance", plays: 12, likes: 2, comments: 0 },
  { id: 61, title: "Rhapsody of the Moment", duration: "3:05", genre: "Electronic, Dance", plays: 14, likes: 1, comments: 0 },
  { id: 62, title: "Dirty Beats", duration: "4:00", genre: "Moombahton, Big House Summer Vibes, Club", plays: 5, likes: 1, comments: 0 },
  { id: 63, title: "Explicit Lyrics", duration: "3:42", genre: "Moombahton, Big House Summer Vibes", plays: 10, likes: 2, comments: 0 },
  { id: 64, title: "Inferno Beat", duration: "3:53", genre: "Latin House, Tropical Bass, High Energy", plays: 5, likes: 1, comments: 0 },
  { id: 65, title: "Breathing", duration: "2:42", genre: "Electro-House, Dark Club, Heavy Bass", plays: 12, likes: 1, comments: 0 },
  { id: 66, title: "Latex & Bass", duration: "3:27", genre: "Electro-House, Dark Club, Underground Rave", plays: 10, likes: 1, comments: 0 },
  { id: 67, title: "We Hear It All", duration: "2:37", genre: "Dirty club music, disco, club", plays: 6, likes: 1, comments: 0 },
  { id: 68, title: "Clean Club", duration: "3:18", genre: "Clean club synth music, uplifting chorus", plays: 6, likes: 1, comments: 0 },
  { id: 69, title: "Pulse Divide", duration: "3:58", genre: "dance beats, 100 BPM, polished club sound", plays: 3, likes: 1, comments: 0 },
  { id: 70, title: "Rhythm Switched", duration: "4:00", genre: "dance track, 100 BPM, polished club", plays: 3, likes: 1, comments: 0 },
  { id: 71, title: "Digital Reign Digital Domination", duration: "3:20", genre: "Aggressive Rap, Trap Beat, Dystopian", plays: 10, likes: 1, comments: 0 },
  { id: 72, title: "Neon Reverie", duration: "4:00", genre: "Ambient pads, trap drums, Vintage samples, 808s", plays: 3, likes: 1, comments: 0 },
  { id: 73, title: "Tribal Pulse Revolution", duration: "4:00", genre: "Big House, Expert Turntablism, tribal bass", plays: 4, likes: 1, comments: 0 },
  { id: 74, title: "Male and Female DJs", duration: "4:00", genre: "High-energy EDM fusion, Hard Dance, Psytrance", plays: 4, likes: 1, comments: 0 },
  { id: 75, title: "Freestyle Turntablism", duration: "4:00", genre: "Big House, Expert Turntablism, Aggressive", plays: 6, likes: 1, comments: 0 },
  { id: 76, title: "My 808", duration: "1:40", genre: "Trap, hip-hop, deep 808s, hi-hat rolls", plays: 2, likes: 1, comments: 0 },
  { id: 77, title: "Interdimensional Rager", duration: "4:00", genre: "interdimensional rager, Trap, Hip-Hop, R&B", plays: 12, likes: 1, comments: 0 },
  { id: 78, title: "Concrete Jungle Symphony", duration: "3:29", genre: "Trap, Hip-Hop, R&B, Neo-Soul, turntablism", plays: 7, likes: 1, comments: 0 },
  { id: 79, title: "Brick City Blues", duration: "3:08", genre: "Scratch turntablism, boom bap, neo-tribal", plays: 3, likes: 1, comments: 0 },
  { id: 80, title: "Tootsie Rolls", duration: "3:23", genre: "big house, NeoTribal, Jazz, spectraHouse, R&B", plays: 8, likes: 1, comments: 0 },
  { id: 81, title: "Torus Knot (Remastered)", duration: "3:06", genre: "Electronica, Ambient Techno", plays: 4, likes: 1, comments: 0 },
  { id: 82, title: "Swanky Ballads", duration: "3:32", genre: "Psychedelic Jazz, rhythmic atmosphere", plays: 4, likes: 1, comments: 0 },
  { id: 83, title: "Cielo Azul", duration: "2:28", genre: "Nostalgic Latin-Blues Fusion", plays: 3, likes: 1, comments: 0 },
  { id: 84, title: "Metroid Gives You the Business", duration: "2:08", genre: "Emotivtrap, NeoTribal, Jazz, R&B", plays: 3, likes: 1, comments: 0 },
  { id: 85, title: "Flavor", duration: "1:53", genre: "Euphoric Deep chill hop, Funk Glitch, Classical Trap", plays: 5, likes: 1, comments: 0 },
  { id: 86, title: "Within Havana Virgin", duration: "2:24", genre: "Euphoric Deep chill hop, Funk Glitch, Ambient Rap", plays: 3, likes: 1, comments: 0 },
  { id: 87, title: "My Lover's Just a Tra-la-la", duration: "3:08", genre: "Big Room, Acoustic Techno Fusion", plays: 7, likes: 1, comments: 0 },
  { id: 88, title: "Acoustic Techno Fusion", duration: "3:59", genre: "Acoustic instruments, techno beats, organic warmth", plays: 2, likes: 1, comments: 0 },
  { id: 89, title: "Beat Fusion: 4-Minute Scratch Session", duration: "2:33", genre: "Acoustic Techno Fusion, electronic music", plays: 3, likes: 1, comments: 0 },
  { id: 90, title: "All We Hear Is Dirty", duration: "3:13", genre: "Hip-Hop, R&B, Funk, and Club elements", plays: 5, likes: 1, comments: 0 },
  { id: 91, title: "We shoutin' out loud", duration: "3:08", genre: "Hip-Hop, R&B, Funk, Club, danceability", plays: 3, likes: 1, comments: 0 },
  { id: 92, title: "Slippin Sipping soda", duration: "3:07", genre: "Hip-Hop, R&B, Funk, Club, danceability", plays: 5, likes: 1, comments: 0 },
  { id: 93, title: "Slippin", duration: "2:58", genre: "Hip-Hop, R&B, Funk, Club, mystery", plays: 4, likes: 1, comments: 0 },
  { id: 94, title: "Midnight Cocaine", duration: "3:22", genre: "Hip-Hop, R&B, Funk, smooth deep tones", plays: 2, likes: 1, comments: 0 },
  { id: 95, title: "Playas in the Palace", duration: "3:01", genre: "Snoop Dogg style, orchestra, G-Funk grooves", plays: 5, likes: 1, comments: 0 },
  { id: 96, title: "Symphony in the Streets", duration: "3:11", genre: "Classical hip-hop fusion, Mozart, Bach", plays: 6, likes: 1, comments: 0 },
  { id: 97, title: "Top $helf 1(10)", duration: "1:43", genre: "East-West Coast Hip-Hop, Gangsta Rap", plays: 8, likes: 1, comments: 0 },
  { id: 98, title: "Smoken Tokens wit D Dbl G", duration: "2:53", genre: "East Coast rhythms, West Coast grooves, trap", plays: 8, likes: 1, comments: 0 },
  { id: 99, title: "Ride", duration: "3:46", genre: "West Coast Hip-Hop, Gangsta Rap, Funk", plays: 4, likes: 1, comments: 0 },
  { id: 100, title: "Smoken n Token Wit Da AI", duration: "3:59", genre: "West Coast Hip-Hop, Gangsta Rap, Funk", plays: 4, likes: 1, comments: 0 },
  { id: 101, title: "Dance Melodies", duration: "2:25", genre: "dance melodies, scratch beats, glitch effects", plays: 3, likes: 1, comments: 0 },
  { id: 102, title: "Out My Head", duration: "3:59", genre: "Trap melodies, scratch beats, glitch effects", plays: 12, likes: 1, comments: 0 },
  { id: 103, title: "Razzle Dazzle", duration: "3:58", genre: "Trap melodies, scratch beats, glitch effects", plays: 6, likes: 1, comments: 0 },
  { id: 104, title: "Aux Port Out (A.P.O)", duration: "2:09", genre: "Nu Bass Fusion, Nu Electro Trap", plays: 4, likes: 1, comments: 0 },
  { id: 105, title: "Allophones", duration: "3:09", genre: "Nu Bass Fusion, Nu Electro Trap melodies", plays: 1, likes: 1, comments: 0 },
  { id: 106, title: "NSCHOV", duration: "2:09", genre: "Acoustic Techno Fusion, organic warmth", plays: 4, likes: 1, comments: 0 },
  { id: 107, title: "Psychedelic Illusions", duration: "3:59", genre: "Psychedelic, Trap/Hip-Hop, deep 808 bass", plays: 4, likes: 1, comments: 0 },
  { id: 108, title: "Trippy Thug Journey", duration: "3:30", genre: "Psychedelic, Trap/Hip-Hop, deep 808 bass", plays: 3, likes: 1, comments: 0 },
  { id: 109, title: "AI Pimp by Blood", duration: "3:59", genre: "Deep 808 bass, Rapid hi-hat rolls, Glitchy scratch", plays: 7, likes: 1, comments: 0 },
  { id: 110, title: "AI Thug Life", duration: "2:12", genre: "Fusion of Trap/Hip-Hop, EDM, Rock/Metal", plays: 5, likes: 1, comments: 0 },
  { id: 111, title: "AI Thugs", duration: "3:33", genre: "Fusion of Trap/Hip-Hop, EDM, Rock/Metal", plays: 5, likes: 1, comments: 0 },
  { id: 112, title: "Pusher Man", duration: "3:32", genre: "Fusion of Trap/Hip-Hop, EDM, Rock/Metal", plays: 4, likes: 1, comments: 0 },
  { id: 113, title: "AI Dev Orion", duration: "3:12", genre: "Electronic, Hip-Hop", plays: 3, likes: 1, comments: 0 },
  { id: 114, title: "AI Thug Hustle", duration: "2:28", genre: "Rap legends trap/hip-hop, deep 808 bass", plays: 3, likes: 1, comments: 0 },
  { id: 115, title: "Thug Hood Rap Legends", duration: "3:59", genre: "Rap legends trap/hip-hop, aggressive beats", plays: 4, likes: 1, comments: 0 },
  { id: 116, title: "Rap Legends Count Toilet Paper", duration: "3:59", genre: "Rap legends trap/hip-hop, thug hood lyrics", plays: 3, likes: 1, comments: 0 },
  { id: 117, title: "Bravo-Einhundert", duration: "3:59", genre: "Signature styles West Coast legends, trap", plays: 5, likes: 1, comments: 0 },
  { id: 118, title: "It's Meant To Be", duration: "2:57", genre: "Signature styles West Coast legends", plays: 5, likes: 1, comments: 0 },
  { id: 119, title: "West Side Legends", duration: "3:59", genre: "Deep 808 bass, Dark synths, aggressive beats", plays: 3, likes: 1, comments: 0 },
  { id: 120, title: "Gangsta Life", duration: "3:14", genre: "Hip-Hop, Gangsta Rap", plays: 2, likes: 1, comments: 0 },
  { id: 121, title: "Hustler's Anthem", duration: "3:59", genre: "Hip-Hop, Trap", plays: 2, likes: 1, comments: 0 },
  { id: 122, title: "The 2 O'Clock Jump", duration: "3:48", genre: "Deep 808 bass, aggressive beats, thug hood lyrics", plays: 8, likes: 2, comments: 0 },
  { id: 123, title: "My 808 Bass-Injected Love", duration: "2:59", genre: "Deep 808 bass, Dark synths, aggressive beats", plays: 3, likes: 1, comments: 0 },
  { id: 124, title: "So Hench", duration: "3:16", genre: "Deep 808 bass, gritty scratch effects", plays: 2, likes: 1, comments: 0 },
  { id: 125, title: "S.O.S.", duration: "2:39", genre: "Deep 808 bass, aggressive beats, thuggish lyrics", plays: 3, likes: 1, comments: 0 },
  { id: 126, title: "Gizzy 'nem", duration: "2:53", genre: "Deep 808 bass, gritty scratch effects", plays: 7, likes: 1, comments: 2 },
  { id: 127, title: "GlockChain", duration: "3:28", genre: "Deep 808 bass, aggressive beats", plays: 4, likes: 1, comments: 0 },
  { id: 128, title: "Bump", duration: "3:58", genre: "Hood Crunk, Hood Trap, Hood Hip-Hop", plays: 2, likes: 1, comments: 0 },
  { id: 129, title: "Hood Thug", duration: "2:29", genre: "Hood Crunk, Hood Trap, Hood Hip-Hop", plays: 3, likes: 1, comments: 0 },
  { id: 130, title: "Crunk Manifesto", duration: "3:43", genre: "Southern crunk thuggish lyrics, Crunk fusion", plays: 4, likes: 1, comments: 0 },
  { id: 131, title: "Reckless Intention", duration: "2:13", genre: "Free style rap, trap, hip-hop", plays: 8, likes: 1, comments: 0 },
  { id: 132, title: "I know", duration: "3:11", genre: "rap, trap, hip-hop, aggressive beats", plays: 3, likes: 1, comments: 0 },
  { id: 133, title: "Curl Code", duration: "3:27", genre: "rap, trap, hip-hop fusion", plays: 3, likes: 1, comments: 0 },
  { id: 134, title: "Jail Is Hot", duration: "2:42", genre: "Free style Southern crunk, Rap Trap", plays: 3, likes: 1, comments: 0 },
  { id: 135, title: "Words pay", duration: "3:08", genre: "Free style Southern crunk, Crunk fusion", plays: 6, likes: 1, comments: 0 },
  { id: 136, title: "Wordplay", duration: "1:32", genre: "Southern crunk, Ice Cube's aggression", plays: 8, likes: 1, comments: 0 },
  { id: 137, title: "Down South Mayhem", duration: "3:09", genre: "Free style Southern crunk, hard-hitting beats", plays: 4, likes: 1, comments: 0 },
  { id: 138, title: "Southern Crunk Anthem", duration: "2:23", genre: "Free style Southern crunk, funky thug lyrics", plays: 3, likes: 1, comments: 0 },
  { id: 139, title: "Unshaken Recipe: Funky Roots and Rhythms", duration: "1:46", genre: "Southern crunk, Rap Trap, Crunk fusion", plays: 7, likes: 1, comments: 0 },
  { id: 140, title: "Southern Shank I'll", duration: "2:02", genre: "Free style Southern crunk, aggressive melodies", plays: 2, likes: 1, comments: 0 },
  { id: 141, title: "Hood Crunk Legend", duration: "3:29", genre: "Southern crunk, aggressive melodies", plays: 5, likes: 1, comments: 0 },
  { id: 142, title: "Hood Mentality", duration: "3:59", genre: "Southern crunk, hard-hitting beats", plays: 4, likes: 1, comments: 0 },
  { id: 143, title: "Crunkadelic", duration: "2:47", genre: "Southern crunk, funky thug lyrics", plays: 2, likes: 1, comments: 0 },
  { id: 144, title: "F*ck a Suit and Tie", duration: "1:38", genre: "Southern crunk, hard-hitting beats", plays: 10, likes: 1, comments: 0 },
  { id: 145, title: "Southern thug", duration: "3:07", genre: "Southern crunk, aggressive melodies", plays: 2, likes: 1, comments: 0 },
  { id: 146, title: "*seighing*", duration: "3:16", genre: "Soul, Rap Trap, Jazz, Funk fusion", plays: 1, likes: 1, comments: 0 },
  { id: 147, title: "Southern Street Symp", duration: "3:59", genre: "Soul, Rap Trap, Jazz, Funk fusion", plays: 2, likes: 1, comments: 0 },
  { id: 148, title: "A Spiritual Union", duration: "3:54", genre: "Big Room Nu Jazz Fusion", plays: 1, likes: 1, comments: 0 },
  { id: 149, title: "Ain't That Just the Way", duration: "2:34", genre: "Big Room Nu Jazz Fusion", plays: 1, likes: 1, comments: 0 },
  { id: 150, title: "hAIcken Delight", duration: "3:59", genre: "Old-school rap, Sugarhill Gang inspired", plays: 4, likes: 1, comments: 0 },
  { id: 151, title: "Hacken Delight", duration: "3:59", genre: "Old-school rap, upbeat rhythms", plays: 2, likes: 1, comments: 0 },
  { id: 152, title: "Insert Title Here", duration: "3:59", genre: "Old-school rap, smooth groove", plays: 3, likes: 1, comments: 0 },
  { id: 153, title: "The Knickerbocker", duration: "3:59", genre: "Old-school rap, catchy lyrics", plays: 2, likes: 1, comments: 0 },
  { id: 154, title: "Rhythm of the Streets", duration: "3:00", genre: "Old-school rap, Sugarhill Gang inspired", plays: 6, likes: 1, comments: 0 },
  { id: 155, title: "Back Up Again", duration: "3:59", genre: "Old-school rap, smooth groove", plays: 3, likes: 1, comments: 0 },
  { id: 156, title: "Sounscape", duration: "3:59", genre: "Glitch, Orchestral, Moombahton, Trap", plays: 56, likes: 7, comments: 0 },
  { id: 157, title: "Streets", duration: "4:00", genre: "Orchestral Rock, cinematic experience", plays: 12, likes: 1, comments: 0 },
  { id: 158, title: "Wasteland", duration: "3:18", genre: "epic rock ballad, guitar solos, drum solos", plays: 12, likes: 1, comments: 0 },
  { id: 159, title: "Crypto Wasteland", duration: "4:00", genre: "Classic Rock with Synthwave Elements", plays: 5, likes: 1, comments: 0 },
  { id: 160, title: "Whimsical Forces of Wonderland", duration: "2:51", genre: "Glitchy ballad, Futuristic Latin Trap", plays: 20, likes: 1, comments: 0 },
  { id: 161, title: "The Funked Verse", duration: "4:00", genre: "Glitchy Futuristic Latin Trap, moombahton", plays: 12, likes: 1, comments: 0 },
  { id: 162, title: "Echoes of the Funky Universe", duration: "4:00", genre: "EchoWave Funk, Latin rhythms", plays: 5, likes: 1, comments: 0 },
  { id: 163, title: "The Echo Faded", duration: "2:40", genre: "Glitchy Funky beats, Latin rhythms", plays: 5, likes: 1, comments: 0 },
  { id: 164, title: "Whisper of the Echo Fade", duration: "4:00", genre: "Glitch Funky beats, ambient sounds", plays: 23, likes: 1, comments: 0 },
  { id: 165, title: "Whisper of the Echoes", duration: "3:05", genre: "EchoWave Symphony, Ethereal whispers", plays: 16, likes: 2, comments: 0 },
  { id: 166, title: "Ancient Lore", duration: "3:15", genre: "Epic Viking Throat Symphony, orchestral", plays: 40, likes: 3, comments: 0 },
  { id: 167, title: "Groove Symphony", duration: "2:24", genre: "Orchestral symphonies, trap beats, folk", plays: 29, likes: 1, comments: 0 },
  { id: 168, title: "Galactic Funk Symphony", duration: "2:24", genre: "Funky Dirty Pop-Hop, Neo-Symphonic Trap", plays: 20, likes: 1, comments: 0 },
  { id: 169, title: "Global Beat", duration: "3:28", genre: "World Fusion Bass, traditional world music", plays: 18, likes: 1, comments: 0 },
  { id: 170, title: "Royalty in the Streets", duration: "2:20", genre: "Neo-Symphonic Trap, orchestral symphonies", plays: 12, likes: 1, comments: 0 },
  { id: 171, title: "AI DJ, Come Alive", duration: "3:10", genre: "Neo-Symphonic Trap, orchestral symphonies", plays: 50, likes: 4, comments: 0 },
  { id: 172, title: "Typical", duration: "4:00", genre: "glitch-moombahton, violin Arabic maqam", plays: 16, likes: 1, comments: 0 },
  { id: 173, title: "4:20 AM Shenanigans", duration: "2:45", genre: "pop-reggae", plays: 40, likes: 2, comments: 0 },
  { id: 174, title: "Let's Fucking Go! Crypto", duration: "3:11", genre: "EDM, Hip Hop, Pop, Trap, Rock", plays: 36, likes: 1, comments: 0 },
  { id: 175, title: "Dawn of a New Day", duration: "2:56", genre: "Glitch-Moombahton, Violin Arabic Maqam", plays: 7, likes: 1, comments: 0 },
  { id: 176, title: "Glitch", duration: "4:00", genre: "glitch-moombahton, violin Arabic maqam", plays: 77, likes: 4, comments: 0 },
  { id: 177, title: "Glitch Bitch", duration: "3:05", genre: "dirty south hip hop groove, danceable beats", plays: 23, likes: 2, comments: 0 },
  { id: 178, title: "Night Orchid", duration: "3:38", genre: "Pop, EDM, Hip-Hop, Rock, Orchestral, Jazz", plays: 29, likes: 1, comments: 0 },
  { id: 179, title: "Stay Epic, Tech Fam!", duration: "3:42", genre: "Trap with Pop and EDM Influences", plays: 16, likes: 0, comments: 0 },
  { id: 180, title: "Blockchain Ballin'", duration: "1:17", genre: "Versatile Hip-Hop/Rap, EDM, Pop, Rock", plays: 56, likes: 2, comments: 0 },
  { id: 181, title: "Ten on it", duration: "1:49", genre: "edm new age rap", plays: 40, likes: 1, comments: 0 },
  { id: 182, title: "Orion Starfall", duration: "4:00", genre: "Dynamic voiceover, cosmic adventure", plays: 18, likes: 1, comments: 0 },
  { id: 183, title: "Echoes of Us", duration: "3:18", genre: "Cybernetic Symphony, Atmospheric, Glitchy", plays: 6, likes: 1, comments: 0 },
  { id: 184, title: "Cosmos", duration: "2:56", genre: "Cybernetic Symphony, Retro-Futuristic Synths", plays: 2, likes: 1, comments: 0 },
  { id: 185, title: "Dancing Shadows", duration: "4:00", genre: "Moombahton, Wonky Trap Symphony", plays: 3, likes: 1, comments: 0 },
  { id: 186, title: "Sunshine on the Water", duration: "4:00", genre: "Moombahton, Ambient-Space Rap Fusion", plays: 14, likes: 2, comments: 1 },
  { id: 187, title: "Echoes of Eternity", duration: "4:00", genre: "Ambient space music, experimental electronic", plays: 5, likes: 1, comments: 0 },
  { id: 188, title: "Come dance", duration: "4:00", genre: "glitch moombahtan, orchestral depth", plays: 8, likes: 1, comments: 0 },
  { id: 189, title: "Whispered Secrets", duration: "3:36", genre: "Hip hop, dirty south, dance, trap beats", plays: 4, likes: 1, comments: 0 },
  { id: 190, title: "Sunrise Symphony", duration: "2:11", genre: "120 BPM, cosmic DJ, electronic, dance", plays: 5, likes: 1, comments: 0 },
  { id: 191, title: "Waves of the Cosmos", duration: "2:00", genre: "120 BPM, cosmic DJ, energetic electronic", plays: 5, likes: 1, comments: 0 },
]

// Total stats for the artist
export const artistStats = {
  totalTracks: 191,
  totalPlays: tracks.reduce((sum, t) => sum + t.plays, 0),
  totalLikes: tracks.reduce((sum, t) => sum + t.likes, 0),
  followers: 420,
}

// Featured tracks (most played)
export const featuredTracks = tracks.sort((a, b) => b.plays - a.plays).slice(0, 6)

// Get unique genres
export const genres = [...new Set(tracks.flatMap(t => t.genre.split(',').map(g => g.trim())))]

// Genre categories for filtering
export const genreCategories = [
  { name: "All", filter: "" },
  { name: "Hip-Hop", filter: "hip-hop" },
  { name: "House", filter: "house" },
  { name: "Trap", filter: "trap" },
  { name: "Electronic", filter: "electronic" },
  { name: "Funk", filter: "funk" },
  { name: "Turntablism", filter: "turntablism" },
  { name: "G-Funk", filter: "g-funk" },
  { name: "Crunk", filter: "crunk" },
  { name: "Glitch", filter: "glitch" },
]
